name: Deploy

on:
  push:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use NodeJS v12.18.3
        uses: actions/setup-node@v1
        with:
          node-version: "12.18.3"
      
      - name: Run deploy.ts
        run: cd scripts && npm install && npm run deploy

      - name: Commit files
        run: |
          git config --local user.email "bot@zyrouge.gq"
          git config --local user.name "Beep Boop [bot]"
          git add .
          git commit -m "🏗️ Build files"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
